import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { SideBar } from "./components/sideBar";
import { Header } from "./components/header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Next Note",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="zh">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-w-[1080px] flex flex-col">
          <Header />
          <div className="flex flex-row flex-1 overflow-y-auto">
            <div className="min-w-[30%]">
              <SideBar />
            </div>
            <div className="dark:bg-slate-800 bg-white px-3 flex-1">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
